---
css: css/styles.css
format:
  html:
    anchor-sections: false
---

::: {.textbox}
# Reviews

Did you ever wonder what other people say about our services? No more, check out some reviews below! More are visible in our [#service-review](https://discord.com/channels/1088746118227165246/1090295820026396854) channel on our [discord server](https://discord.gg/VBA4hbkzVY).


::: {.callout-tip}
## Temple of Febe Legendary CM, 27.05.2024

Thank you for the smooth Febe LCM kill. The whole group was super nice and explained the whole process. Would definitely recommend to others!
:::

::: {.callout-tip}
## Temple of Febe Legendary CM, 07.05.2024

Super smooth and friendly! I told the team that I would keep them in touch for future contents as well (I did Febe Legendary challenge mode). Super happy with the service. Thank you guys once again, yall amazing!   EDIT: forgot to mention that i come from US server and they made it super easy to transfer to EU server, basically guided me thru the whole process. thank you again guys! 
:::

::: {.callout-tip}
## Harvest Temple CM - Voidwalker & Kaineng Overlook CM, 09.04.2024

Thanks for the run (HT and KO), all went perfectly (and it's always a pleasure to look at players so much better than me play hard content !)
Now I need to save for Cerus !
:::


::: {.callout-tip}
## Harvest Temple CM - Voidwalker, 26.01.2024

Extremely fast delivery with HTCM, smooth run. I highly recommend the team 🙂
:::

::: {.callout-tip}
## Old Lions Court CM - Title Achievement, 27.12.2023

Great Old Lion Arch title run this evening!
Smooth and clean 🙂
Thanks again!
:::

::: {.callout-tip}
## Harvest Temple CM - Voidwalker, 22.09.2023

I know my stuff. These guys know it more. Legitimately the best 10 man execution I've ever seen. 
Bonus points for the memes, too. 
A+
:::

::: {.callout-tip}
## Harvest Temple CM - All Achievements, 03.06.2023

Thanks for the all achievements HT CM. It was divine. Better call UNIT for service!
:::

::: {.callout-tip}
## Harvest Temple CM - All Achievements, 13.05.2023

Thanks so much for the HTCM (Voidwalker+Standing Together) clear! Very fast and smooth, thank you for all the detailed explanations as well as for being so responsive! 
:::

::: {.callout-tip}
## Harvest Temple CM - Voidwalker, 14.04.2023

Hey guys! Tyvm for the HTCM. You are realy cool guys! It was fun and I'm really happy about it! It was worth every coin! 🙂
:::

::: {.callout-tip}
## Harvest Temple CM - All Achievements, 02.04.2023

Hey i bought the HTCM with all Achievements, good service fast run!. Thank you again ^^

:::
:::